version: 2

jobs:
  checkout_code:
    working_directory: ~/repo
    docker:
      - image: circleci/node:6.17.0
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  install_deps:
    working_directory: ~/repo
    docker:
      - image: circleci/node:6.17.0
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  run_test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:6.17.0
    environment:
      JEST_JUNIT_OUTPUT: reports/jest/summary.xml
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn test
      - save_cache:
          key: coverage-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - coverage
      - store_test_results:
          path: reports

  coverage:
    working_directory: ~/repo
    docker:
      - image: circleci/node:6.17.0
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: coverage-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn codecov


workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_code
      - install_deps:
          requires:
            - checkout_code
      - run_test:
          requires:
            - install_deps
      - coverage:
          requires:
            - run_test
